## build stage
FROM microsoft/aspnetcore-build:2 as build-env

WORKDIR /generator 

# restore this is only for dependencies!!!!!!  put stuff that is going to change to be at the bottom ./api. refers to the containers folder
COPY api/api.csproj ./api/
RUN dotnet restore api/api.csproj

COPY api/tests/tests.csproj ./test/
RUN dotnet restore test/tests.csproj

##recursely list out files of working directory
RUN ls -alR

# copy src
COPY . . 

# test
# the path is that of the source code
RUN dotnet test api/tests/tests.csproj

# publish

RUN dotnet publish api/api.csproj -o /publish


## runtine stage


FROM microsoft/aspnetcore:2
COPY --from=build-env /publish /publish
WORKDIR /publish
ENTRYPOINT ["dotnet", "api.dll"]

